name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: install pytest
      run: |
        pip install pytest==6.0.1 requests==2.24.0
    - name: make build
      run: |
        make build
    - name: install requirements
      run: |
        pip install -r requirements.txt
    - name: make test
      run: |
        make test